### ISSUE TITLE
Tracking: Personal google trace

### ISSUE THREAD

**Issue by mitra42** [mitra42/corona-tracker#17]
It looks like on https://pandemic.events/# that they have a way to grab kml files for your own location. I've not explored this in detail, but its is potentially interesting, 

I think the task is 
- [ ] figure out how they are doing it - write it up below. 
- [ ] see if we can find an easy way to, from a web page, grab that data and feed it up to our server
- [ ] on the server, add a way to turn kml into a standard set of geolocations. 
- [ ] then integrate that with any matching we are doing (once its ready). 

Anyone want to take this ?

**Comment by Stimim** [comment]
1. => we (dynamically) generate links, and simulate click events to trigger downloading.
2. => I'm afraid not. Browser should stop you from doing that (e.g. using "Request()" API to download the file to memory directly).  Otherwise an attacker can perform do this and silently upload your data to their server.
3 => You can check our KML parsers, I hope the code is documented well enough.

**Comment by mitra42** [comment]
Thanks - I'll take a look at your code.

**Comment by olivernash** [comment]
Hello, this project looks great. Well done! 

I tried building the repo yesterday evening and I'm issues setting it up. It was just a white screen after I run node. Also in terms of the instructions, I think it should be cd into to the server directory, rather than src.

**Comment by mitra42** [comment]
Thanks Oliver - yes I just uploaded a new README with that instruction fixed, the client side is definately still experimental - we've been focusing on the data side - both getting data sets and looking at how to upload to the activity trackers. To start with, so for example if you run Node you should then be able to go to http://localhost:5000/data/israel?output=takeout to get the Israeli data set converted to the Takeout format. 

I'm exhausted and need to stop for the night, if we are on the same timezone in about 11 hours or more then I'll happily share a screen and figure out what is going wrong.

**Comment by olivernash** [comment]
Thanks Mitra - that all makes sense. I thought there might be a front end
part and hadn't checked sufficiently. I will take another look at it this
afternoon.

**Comment by mitra42** [comment]
Great - feel free to start new issues if you hit problems.
